# Generated by Django 3.2.12 on 2022-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='todo.ProjectUser', verbose_name='Пользователи'),
        ),
    ]
